name: Validate Atlas

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-atlas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Validate Atlas
        run: python atlas/tools/validate-atlas.py
